# Generated by Django 4.1 on 2022-09-11 01:48

import app.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BA', 'Barceloneta'), ('LP', 'Las Piedras'), ('SA', 'Santurce'), ('SG', 'San Germán'), ('SL', 'Salinas')], max_length=2, verbose_name='Sucursal')),
                ('address1', models.CharField(max_length=30)),
                ('address2', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=9)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('fax', phone_field.models.PhoneField(blank=True, help_text='Contact fax number', max_length=31)),
                ('manager', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='images/')),
                ('maplink', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Pueblo')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.branch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.branch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobID', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('posting_date', models.DateField(blank=True, default=datetime.date.today, help_text='Enter posting date', null=True, validators=[app.models.no_pass])),
                ('closing_date', models.DateField(blank=True, help_text='Enter the closing date', null=True, validators=[app.models.no_pass])),
                ('created_date', models.DateTimeField(blank=True, default=datetime.date.today)),
                ('recruiter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.recruiter')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.town')),
            ],
        ),
    ]
