# Generated by Django 4.1 on 2022-08-31 18:01

import app.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="closing_date",
            field=models.DateField(
                blank=True,
                help_text="Enter the closing date",
                null=True,
                validators=[app.models.no_pass],
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="created_date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="job",
            name="posting_date",
            field=models.DateField(
                blank=True,
                default=datetime.datetime.now,
                help_text="Enter posting date",
                null=True,
                validators=[app.models.no_pass],
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="recruiter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="app.recruiter"
            ),
        ),
        migrations.AlterField(
            model_name="recruiter",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="description",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="town",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="app.branch"
            ),
        ),
        migrations.AlterField(
            model_name="town",
            name="name",
            field=models.CharField(max_length=20, unique=True, verbose_name="Pueblo"),
        ),
    ]
