# Generated by Django 4.1 on 2022-09-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.ManyToManyField(blank=True, to='app.requirement'),
        ),
    ]
