# Generated by Django 4.1 on 2022-08-31 18:56

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_job_closing_date_alter_job_posting_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="closing_date",
            field=models.DateField(
                blank=True,
                help_text="Enter the closing date",
                null=True,
                validators=[app.models.no_pass],
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="created_date",
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="job",
            name="posting_date",
            field=models.DateField(
                blank=True,
                default=datetime.date.today,
                help_text="Enter posting date",
                null=True,
                validators=[app.models.no_pass],
            ),
        ),
    ]
