# Generated by Django 4.1 on 2022-08-31 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_job_closing_date_alter_job_created_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job", old_name="requiremets", new_name="requirements",
        ),
    ]
