# Generated by Django 4.1 on 2022-09-01 04:06

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_requiremets_job_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='posting_date',
            field=models.DateField(auto_now_add=True, help_text='Enter posting date', null=True, validators=[app.models.no_pass]),
        ),
    ]
