# Generated by Django 4.1 on 2022-09-01 04:20

import app.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_job_created_date_alter_job_posting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='job',
            name='posting_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Enter posting date', null=True, validators=[app.models.no_pass]),
        ),
        migrations.AlterField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.recruiter'),
        ),
    ]
